import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import {pathToFileURL} from 'node:url';
import {payload} from '../runtime/BP/scripts/payload.js';import {withFoundation} from '../runtime/BP/scripts/foundation.js';import {buildRegistrationPayload,OPTIONAL_COOKERY_RECIPES} from '../runtime/BP/scripts/optional-cookery.js';
const host=pathToFileURL(path.resolve(process.env.TAVERN_ROOT??'../tavern-src')+'/');
const {ExtensionRegistry}=await import(new URL('runtime/BP/scripts/core/registry.js',host));const {BUILTIN_RECIPES}=await import(new URL('runtime/BP/scripts/data/recipes.js',host));const {SHAKER_RECIPES}=await import(new URL('runtime/BP/scripts/data/mixology.js',host));const {FLUIDS}=await import(new URL('runtime/BP/scripts/data/fluids.js',host));const {buildCookeryGuidePayload}=await import(new URL('runtime/BP/scripts/data/cookery-guide-payload.js',host));
const {standaloneGuideView}=await import(new URL('runtime/BP/scripts/core/standalone-guide-model.js',host));
function registry(itemExists){return new ExtensionRegistry({recipes:[...BUILTIN_RECIPES,...SHAKER_RECIPES],fluids:FLUIDS,itemExists});}
for(const rice of [false,true])for(const panicle of [false,true])test('strict registration with rice='+rice+' panicle='+panicle,()=>{
 const exists=id=>id==='kaleidoscope_cookery:rice'?rice:id==='kaleidoscope_cookery:rice_panicle'?panicle:!id.startsWith('kaleidoscope_cookery:');const before=JSON.stringify(payload),p=buildRegistrationPayload(payload,exists),r=registry(exists);r.install(withFoundation(p));assert.equal(p.recipes.length,payload.recipes.length-(rice?0:1)-(panicle?0:1));assert.equal(p.pages.length,67);assert.deepEqual(p.content,payload.content);assert.deepEqual(p.shakerInputs,payload.shakerInputs);assert.equal(JSON.stringify(payload),before);
 const guide=buildCookeryGuidePayload(r);assert.equal(guide.entries.length,223);assert.equal(guide.categories.length,31);
 for(const rule of OPTIONAL_COOKERY_RECIPES){const available=exists(rule.item),page=p.pages.find(x=>x.id===rule.page),entry=guide.entries.find(x=>x.id===page.item);assert.equal((entry.recipes??[]).length,available?1:0);for(const locale of ['en_US','zh_CN','zh_TW']){const v=standaloneGuideView(guide,locale,{type:'entry',id:entry.id});assert.equal(v.buttons.filter(x=>x.action.type==='recipe').length,available?1:0);if(!available)assert.ok(page.body[locale].includes(rule.names[locale]));}}
 if(rice&&panicle)assert.equal(p,payload);
});
test('missing unrelated ingredient still fails strict validation',()=>{const exists=id=>id!=='minecraft:bamboo';const p=buildRegistrationPayload(payload,exists);assert.equal(p,payload);assert.throws(()=>registry(exists).install(withFoundation(p)),/UNKNOWN_ITEM/);});
test('future matching preparation removed but other methods retained',()=>{const raw=structuredClone(payload),rule=OPTIONAL_COOKERY_RECIPES[0],page=raw.pages.find(p=>p.id===rule.page);page.preparations=[{method:'Barrel',ingredients:[rule.item]},{method:'Freezer',ingredients:['minecraft:snowball']},{method:'Barrel',ingredients:['minecraft:wheat']}];const result=buildRegistrationPayload(raw,id=>id!==rule.item);assert.deepEqual(result.pages.find(p=>p.id===rule.page).preparations,page.preparations.slice(1));});
test('item registry lookup failure is not disguised as optional absence',()=>{assert.throws(()=>buildRegistrationPayload(payload,()=>{throw Error('registry unavailable')}),/registry unavailable/);});
